baseURL = 'https://hugoaguirre.github.io/gouh'
languageCode = 'en-us'
title = 'Gouh'
theme = 'archie'

# Code highlights
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
  mode="toggle"
  useCDN=false
  subtitle="A blog made of my random stuff + info about me"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hugoaguirre"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/huugooe"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://mx.linkedin.com/in/hugo-aguirre-parra-11504780"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "/about"
weight = 3
